## Variaveis constantes

In [2]:
numero = -3
numero_J = 14
numero_C = 15

In [3]:
numero

-3

In [4]:
numero_C

15

In [5]:
numero_J

14

In [6]:
print(numero, numero_C, numero_J)

-3 15 14


In [10]:
pi = 3.14
numero_e = 2.71
escala_t = - 4.55

In [11]:
print(pi, numero_e, escala_t)

3.14 2.71 -4.55


In [23]:
letter = 'a'
palavra = 'LDP'
palavra2 = 'Py'

In [24]:
print(palavra, letter, palavra2)

LDP a Py


In [25]:
print("Isto é", palavra2)

Isto é Py


#Você pode user float, int, string(para transformar em caracteer)

In [40]:
altura = float(input("Digie sua altura?"))
print('Sua idade é', altura, 'cm')

Sua idade é 1.65 cm


In [41]:
altura

1.65

In [32]:
idade = str(input("Digie sua idade ?"))
print('Sua idade é', idade)

Sua idade é 30


In [33]:
idade

'30'

In [28]:
ph = int(input("Ph so Solo?"))
print(' O PH é ', ph)

 O PH é  30


In [31]:
ph

30

In [42]:
a, b = 5, 3
print(a,b)

5 3


In [43]:
a + b

8

In [44]:
a / b

1.6666666666666667

In [45]:
a * b

15

In [46]:
a % b

2

In [48]:
a** b

125

In [52]:
import math
math.sqrt(81)

9.0

Arredondamento

In [54]:
casos_doenca = 134
numero_Hab = 34432

casos_Localidade = casos_doenca / numero_Hab

print(casos_Localidade)

0.003891728624535316


In [58]:
round(casos_Localidade, 4)

0.0039

## Operadores Logicos relacionais

In [61]:
a,b = True, False

In [62]:
print(a,b)

True False


In [63]:
a and b

False

In [64]:
b & b

False

In [65]:
c = a and b

In [66]:
print(c)

False


In [67]:
a or b 

True

In [68]:
a | b

True

# Operadores Relacionais

In [69]:
5 > 3

True

In [70]:
4 > 4

False

In [71]:
3 < 5

True

In [73]:
8 > 10 

False

In [74]:
5 !=5

False

## Operador Condicional

In [76]:
a,b =  10, 11

if a > b:
    print(a)
else:
    print('Lascouse')

Lascouse


In [79]:
5 > 3

if 5 > 3:
    print('Maior é 5 ')

Maior é 5 


In [94]:
numero = int(input('Digite um numero:?'))

if numero > 100:
    print('É maior',numero)
else:
    print('Não é maior', numero)
    if numero == 10:
        print('é igual a dezena')
    else:
        numero -=1 #incrementar o valor de numero
        print('Incrementado', numero)

Não é maior 50
Incrementado 49


In [98]:
x , y = 2, 3 

if (x > 1) and (y % 2 == 0):
    print('X é maior que 1 e y é par')
else:
    print('Não há condição verdadeira')

Não há condição verdadeira


## Estrutura repetição for, while


In [99]:
print('*')
print('**')
print('***')
print('*****')
print('******')

*
**
***
*****
******


In [100]:
print(1)
print(2)
print(3)
print(4)
print(5)

1
2
3
4
5


In [104]:
for i in range(1,5):
    print(i+1)

2
3
4
5


In [106]:
for numero in range(5, 0, -1):
    print("Numero: ", numero)

Numero:  5
Numero:  4
Numero:  3
Numero:  2
Numero:  1


In [112]:
soma = 0
for numero in range (1,6):
    soma = soma + numero
    print(soma)
    print("A soma dos numeros de 1 ate 5 e:", soma)
print(soma)

1
A soma dos numeros de 1 ate 5 e: 1
3
A soma dos numeros de 1 ate 5 e: 3
6
A soma dos numeros de 1 ate 5 e: 6
10
A soma dos numeros de 1 ate 5 e: 10
15
A soma dos numeros de 1 ate 5 e: 15
15


In [115]:
palavra = "ICe Creme"

for letra in palavra:
    print(letra)
    if letra == 'C':
        print('Achei')
    

I
C
Achei
e
 
C
Achei
r
e
m
e


In [ ]:
n = 1
while n < 6:
    print(n)
    numero += 1

## Função de Parametros de passagem

In [122]:
def soma(a,b):
    print(a+b)

In [124]:
soma (2, 4)

6


In [126]:
def mensagem(texto):
    print(texto)
    
mensagem('TEste')
mensagem('teste')

TEste
teste


MAtryzes numpy

In [128]:
import numpy as np

In [130]:
matriz = np.array([[2, 3,1], 
                   [4,5,6]])

In [132]:
matriz

array([[2, 3, 1],
       [4, 5, 6]])

In [133]:
matriz.shape

(2, 3)

In [134]:
matriz[0]

array([2, 3, 1])

In [138]:
matriz[0][1]

3

In [145]:
for i in range(matriz.shape[0]):
    print(matriz[i])
    for j in range(matriz.shape[1]):
     print(matriz[i][j])

[2 3 1]
2
3
1
[4 5 6]
4
5
6
